// Code generated by github.com/gobuffalo/packr. DO NOT EDIT

package fizz

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("./templates", "migration.fizz.tmpl", "\"Y3JlYXRlX3RhYmxlKCJ7ey5OYW1lLlRhYmxlfX0iKSB7CiAge3sgcmFuZ2UgJGEgOj0gLkF0dHJzIH19CiAgdC5Db2x1bW4oInt7JGEuTmFtZS5VbmRlcnNjb3JlfX0iLCAie3skYS5Db21tb25UeXBlfX0iKQogIHt7IGVuZCB9fQp9Cg==\"")
}
