// Code generated by github.com/gobuffalo/packr. DO NOT EDIT

package pop

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("./templates", "models/model.go.plush", "\"cGFja2FnZSBtb2RlbHMKCnR5cGUgPCU9IG1vZGVsLk5hbWUuTW9kZWwoKSAlPiBzdHJ1Y3QgewogIDwlPSBmb3IgKGEpIGluIG1vZGVsLkF0dHJzIHsgJT4KICA8JT0gYS5OYW1lLkNhbWVsKCkgJT4gPCU9IGEuR29UeXBlKCkgJT4KICA8JSB9ICU+Cn0K\"")
}
