name: Tests
on: [push]
jobs:
​  tests-on:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.11.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test
      run: |
        go mod tidy -v
        go test -race ./...
  tests-off:
    name: (GOPATH) ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.11.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      GO111MODULE: off
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: src/github.com/${{ github.repository }}
    - name: Test
      env:
        GOPATH: ${{runner.workspace}}
      run: |
        go get -t -v ./...
        go test -race ./...
